version: '3.8'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: logistics_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: hellopogi0164
      MB_DB_HOST: postgres
